[package]
name = "voice-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
gemini-rust = "1.4.0"
tokio = { version = "1.47.1", features = ["full"] }

[[bin]]
name = "voice-backend"
path = "main.rs"
